language: python
python: 3.6
notifications:
  email: false
sudo: false
matrix:
  include:
    - env: PROJECT=sample SCENARIO=sample
    - env: PROJECT=single_app SCENARIO=single_app
    - env: PROJECT=app_2libs SCENARIO=app_lib
    - env: PROJECT=app_10libs SCENARIO=app_lib
script:
  - make generate
  - ./benchmark.sh $PROJECT $SCENARIO
