language: python
python: 3.6
notifications:
  email: false
sudo: false
env:
  matrix:
    - PROJECT=sample SCENARIO=sample
    - PROJECT=single_app SCENARIO=single_app
    - PROJECT=app_2libs SCENARIO=app_lib
    - PROJECT=app_10libs SCENARIO=app_lib
script:
  - make generate gradle-profiler
  - ./benchmark.sh $PROJECT $SCENARIO
