language: android
android:
  components:
    - build-tools-26.0.1
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
jdk: oraclejdk8
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  matrix:
    - PROJECT=sample SCENARIO=sample
    - PROJECT=single_app SCENARIO=single_app
    - PROJECT=multi_2 SCENARIO=multi_2
    - PROJECT=multi_10 SCENARIO=multi_10
    - PROJECT=multi_100 SCENARIO=multi_100
script:
  - make gradle-profiler
  - python3 -m generator
  - python3 ./gen-scenarios.py
  - ./benchmark.sh $PROJECT $SCENARIO
sudo: false
notifications:
  email: false
