language: android
android:
  components:
    - build-tools-26.0.1
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
jdk: oraclejdk8
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  matrix:
    - PROJECT=sample
    - PROJECT=single_app
    - PROJECT=multi_10
    - PROJECT=multi_30
    - PROJECT=multi_50
    - PROJECT=multi_80
    - PROJECT=multi_100
script:
  - make gradle-profiler
  - python3 ./gen-projects.py $PROJECT
  - python3 ./gen-scenarios.py
  - ./benchmark.sh $PROJECT $PROJECT
sudo: false
notifications:
  email: false
